services:
  - type: web
    name: hospital-patient-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 1000
      - key: MONGODB_URI
        value: mongodb+srv://Aditya:ridhima0202@cluster0.keo36br.mongodb.net/?appName=Cluster0
